// src/components/Footer.jsx
function Footer() {
	return (
		<footer className="container mx-auto py-10 text-right text-sm">
			Built with: <a href="//tailwindcss.com">tailwindcss</a>,{' '}
			<a href="//reactjs.org">React</a>, and <a href="//vue.org">Vue</a>. What?
			React and Vue, how?{' '}
			<a href="//astro.build" target="_blank" rel="noreferrer">
				-> Astro
			</a>
		</footer>
	);
}

export default Footer;

// src/components/Footer.vue
<template>
	<footer class="container mx-auto py-10 text-right text-sm">
		Built with: <a href="//tailwindcss.com">tailwindcss</a> ,
		<a href="//reactjs.org">React</a>, and <a href="//vue.org">Vue</a>. What?
		React and Vue, how? <a href="//astro.build" target="_blank">Astro</a>
	</footer>
</template>

<script>
	export default {}
</script>

<style></style>
